module.exports = [
    {
        msrp: 724,
        spec_level: "Mid-Range",
        category: "Crosscountry",
        weight: "14,1 kg",
        frame: "Aluminum",
        fork: "Suntour XCT",
        wheels: "Aluminum",
        wheel_size: "27.5″ / 29″",
        clearance: '2.2"',
        brakes: "Hydraulic Disc",
        groupset: "Deore",
        drivetrain: "1 × 10",
        suspension: "Hardtail",
        front_travel: "100mm",
        seatpost: "Rigid",
    },
    {
        msrp: 1,
        spec_level: "2",
        category: "3",
        weight: "4",
        frame: "5",
        fork: "6",
        wheels: "7",
        wheel_size: "8",
        clearance: '9',
        brakes: "10",
        groupset: "11",
        drivetrain: "12",
        suspension: "13",
        front_travel: "14",
        seatpost: "15",
    },
];
